#!/usr/bin/env bash
# This script displays list of curently running processes
# Must show all processes, for users, including those whiich might not have a TTY
# Display a user-oriented format

ps -a -x -u -f
